export * from './home';
export * from './profile';
export * from './products';
export * from './orders';
export * from './details-product';
export * from './shipping';
export * from './details-order/details-order-section';
export * from './place-order';
export * from './details-order';
